<?xml version="1.0" encoding="utf-8"?><Database Name="QLThiTracNghiem" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-K4OU33O\CHIENCOOL;Initial Catalog=QLThiTracNghiem;Integrated Security=True" SettingsObjectName="WebTHPT.Properties.Settings" SettingsPropertyName="QLThiTracNghiemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BaiThi" Member="BaiThis">
    <Type Name="BaiThi">
      <Column Name="MaBT" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHS" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="MaDe" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianLam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LanThi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="BaiThi_ChiTietBaiThi" Member="ChiTietBaiThis" ThisKey="MaBT" OtherKey="MaBT" Type="ChiTietBaiThi" />
      <Association Name="DeThi_BaiThi" Member="DeThi" ThisKey="MaDe" OtherKey="MaDe" Type="DeThi" IsForeignKey="true" />
      <Association Name="HocSinh_BaiThi" Member="HocSinh" ThisKey="MaHS" OtherKey="MaHS" Type="HocSinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTin" Member="ThongTins">
    <Type Name="ThongTin">
      <Column Name="MaTT" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTK" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="Char(13) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="NoiSinh" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DanToc" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TonGiao" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="GiaoVien_ThongTin" Member="GiaoVien" ThisKey="MaTK" OtherKey="MaGV" Type="GiaoVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="HocSinh_ThongTin" Member="HocSinh" ThisKey="MaTK" OtherKey="MaHS" Type="HocSinh" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="MaCauHoi" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Association Name="CauHoi_CauHoiDeTHi" Member="CauHoiDeTHis" ThisKey="MaCauHoi" OtherKey="MaCauHoi" Type="CauHoiDeTHi" />
      <Association Name="CauHoi_LuaChon" Member="LuaChons" ThisKey="MaCauHoi" OtherKey="MaCauHoi" Type="LuaChon" />
    </Type>
  </Table>
  <Table Name="dbo.CauHoiDeTHi" Member="CauHoiDeTHis">
    <Type Name="CauHoiDeTHi">
      <Column Name="MaDe" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCauHoi" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CauHoi_CauHoiDeTHi" Member="CauHoi" ThisKey="MaCauHoi" OtherKey="MaCauHoi" Type="CauHoi" IsForeignKey="true" />
      <Association Name="DeThi_CauHoiDeTHi" Member="DeThi" ThisKey="MaDe" OtherKey="MaDe" Type="DeThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietBaiThi" Member="ChiTietBaiThis">
    <Type Name="ChiTietBaiThi">
      <Column Name="MaBT" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLuaChon" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="BaiThi_ChiTietBaiThi" Member="BaiThi" ThisKey="MaBT" OtherKey="MaBT" Type="BaiThi" IsForeignKey="true" />
      <Association Name="LuaChon_ChiTietBaiThi" Member="LuaChon" ThisKey="MaLuaChon" OtherKey="MaLuaChon" Type="LuaChon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeThi" Member="DeThis">
    <Type Name="DeThi">
      <Column Name="MaDe" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDe" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaGV" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayThi" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Association Name="DeThi_BaiThi" Member="BaiThis" ThisKey="MaDe" OtherKey="MaDe" Type="BaiThi" />
      <Association Name="DeThi_CauHoiDeTHi" Member="CauHoiDeTHis" ThisKey="MaDe" OtherKey="MaDe" Type="CauHoiDeTHi" />
      <Association Name="GiaoVien_DeThi" Member="GiaoVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiaoVien" IsForeignKey="true" />
      <Association Name="MonHoc_DeThi" Member="MonHoc" ThisKey="MaMH" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiaChi" Member="DiaChis">
    <Type Name="DiaChi">
      <Column Name="MaDC" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHS" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="TenDC" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTP" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="QuanHuyen" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PhuongXa" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoNha" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="HocSinh_DiaChi" Member="HocSinh" ThisKey="MaHS" OtherKey="MaHS" Type="HocSinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoVien" Member="GiaoViens">
    <Type Name="GiaoVien">
      <Column Name="MaGV" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenGV" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ChuyenNganh" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Association Name="GiaoVien_ThongTin" Member="ThongTins" ThisKey="MaGV" OtherKey="MaTK" Type="ThongTin" />
      <Association Name="GiaoVien_DeThi" Member="DeThis" ThisKey="MaGV" OtherKey="MaGV" Type="DeThi" />
      <Association Name="GiaoVien_GiaoVienLop" Member="GiaoVienLops" ThisKey="MaGV" OtherKey="MaGV" Type="GiaoVienLop" />
      <Association Name="GiaoVien_GiaoVienMonHoc" Member="GiaoVienMonHocs" ThisKey="MaGV" OtherKey="MaGV" Type="GiaoVienMonHoc" />
      <Association Name="GiaoVien_GopY" Member="Gopies" ThisKey="MaGV" OtherKey="MaTK" Type="GopY" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoVienLop" Member="GiaoVienLops">
    <Type Name="GiaoVienLop">
      <Column Name="MaGV" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="GiaoVien_GiaoVienLop" Member="GiaoVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiaoVien" IsForeignKey="true" />
      <Association Name="Lop_GiaoVienLop" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoVienMonHoc" Member="GiaoVienMonHocs">
    <Type Name="GiaoVienMonHoc">
      <Column Name="MaGV" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="GiaoVien_GiaoVienMonHoc" Member="GiaoVien" ThisKey="MaGV" OtherKey="MaGV" Type="GiaoVien" IsForeignKey="true" />
      <Association Name="MonHoc_GiaoVienMonHoc" Member="MonHoc" ThisKey="MaMH" OtherKey="MaMon" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GopY" Member="Gopies">
    <Type Name="GopY">
      <Column Name="MaGopY" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTK" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="GiaoVien_GopY" Member="GiaoVien" ThisKey="MaTK" OtherKey="MaGV" Type="GiaoVien" IsForeignKey="true" />
      <Association Name="HocSinh_GopY" Member="HocSinh" ThisKey="MaTK" OtherKey="MaHS" Type="HocSinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocSinh" Member="HocSinhs">
    <Type Name="HocSinh">
      <Column Name="MaHS" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenHS" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NienKhoa" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Association Name="HocSinh_BaiThi" Member="BaiThis" ThisKey="MaHS" OtherKey="MaHS" Type="BaiThi" />
      <Association Name="HocSinh_ThongTin" Member="ThongTins" ThisKey="MaHS" OtherKey="MaTK" Type="ThongTin" />
      <Association Name="HocSinh_DiaChi" Member="DiaChis" ThisKey="MaHS" OtherKey="MaHS" Type="DiaChi" />
      <Association Name="HocSinh_GopY" Member="Gopies" ThisKey="MaHS" OtherKey="MaTK" Type="GopY" />
      <Association Name="HocSinh_HoSoHocSinh" Member="HoSoHocSinhs" ThisKey="MaHS" OtherKey="MaHS" Type="HoSoHocSinh" />
      <Association Name="HocSinh_PhuHuynh" Member="PhuHuynhs" ThisKey="MaHS" OtherKey="MaHS" Type="PhuHuynh" />
      <Association Name="Lop_HocSinh" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoSo" Member="HoSos">
    <Type Name="HoSo">
      <Column Name="MaHoSo" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHoSo" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="HoSo_HoSoHocSinh" Member="HoSoHocSinhs" ThisKey="MaHoSo" OtherKey="MaHoSo" Type="HoSoHocSinh" />
    </Type>
  </Table>
  <Table Name="dbo.HoSoHocSinh" Member="HoSoHocSinhs">
    <Type Name="HoSoHocSinh">
      <Column Name="MaHS" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHoSo" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="HoSo_HoSoHocSinh" Member="HoSo" ThisKey="MaHoSo" OtherKey="MaHoSo" Type="HoSo" IsForeignKey="true" />
      <Association Name="HocSinh_HoSoHocSinh" Member="HocSinh" ThisKey="MaHS" OtherKey="MaHS" Type="HocSinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Khoi" Member="Khois">
    <Type Name="Khoi">
      <Column Name="MaKhoi" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoi" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Association Name="Khoi_Lop" Member="Lops" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="Lop" />
      <Association Name="Khoi_MonHoc" Member="MonHocs" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="MonHoc" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="MaLop" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoi" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Association Name="Lop_GiaoVienLop" Member="GiaoVienLops" ThisKey="MaLop" OtherKey="MaLop" Type="GiaoVienLop" />
      <Association Name="Lop_HocSinh" Member="HocSinhs" ThisKey="MaLop" OtherKey="MaLop" Type="HocSinh" />
      <Association Name="Khoi_Lop" Member="Khoi" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="Khoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LuaChon" Member="LuaChons">
    <Type Name="LuaChon">
      <Column Name="MaLuaChon" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LaDapAn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaCauHoi" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="LuaChon_ChiTietBaiThi" Member="ChiTietBaiThis" ThisKey="MaLuaChon" OtherKey="MaLuaChon" Type="ChiTietBaiThi" />
      <Association Name="CauHoi_LuaChon" Member="CauHoi" ThisKey="MaCauHoi" OtherKey="MaCauHoi" Type="CauHoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="MaMon" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoi" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="MonHoc_DeThi" Member="DeThis" ThisKey="MaMon" OtherKey="MaMH" Type="DeThi" />
      <Association Name="MonHoc_GiaoVienMonHoc" Member="GiaoVienMonHocs" ThisKey="MaMon" OtherKey="MaMH" Type="GiaoVienMonHoc" />
      <Association Name="Khoi_MonHoc" Member="Khoi" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="Khoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhuHuynh" Member="PhuHuynhs">
    <Type Name="PhuHuynh">
      <Column Name="MaPH" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHS" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="HoTenPH" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="Char(13) NOT NULL" CanBeNull="false" />
      <Association Name="HocSinh_PhuHuynh" Member="HocSinh" ThisKey="MaHS" OtherKey="MaHS" Type="HocSinh" IsForeignKey="true" />
    </Type>
  </Table>
</Database>